catherinetkl/kidstrotter

- db/migrate/20221123035916_add_require_booking_require_payment_and_references_to_activity_table.rb
- db/migrate/20221123040328_add_references_to_activity_table.rb
- db/schema.rb
Migration changes to activity table
> Migration changes to activity table

- app/models/activity.rb
- app/models/booking.rb
- db/migrate/20221122044754_create_bookings.rb
- db/schema.rb
- db/seeds.rb
Fixed seeds, had git pushing issues - solved by ZH
> Fixed seeds

- app/views/activities/index.html.erb
Unused rating, so it's removed.
> FIX - Removed activity.rating from the Activity Index HTML

- app/controllers/application_controller.rb
- app/views/shared/_navbar.html.erb
feature-navbar-edit-and-temporarily-removed-authentication
> feature-navbar-edit-and-temporarily-removed-authentication

- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/views/activities/show.html.erb
- app/views/bookings/index.html.erb
- app/views/bookings/new.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
feature-fixed-devise-issues-and-bookings-index-& readded-authentication
> feature-fixed-devise-issues-and-bookings-index-& readded-authentication

- app/controllers/bookings_controller.rb
- app/views/activities/show.html.erb
- app/views/bookings/new.html.erb
feature-bookings-new-completed
> feature-bookings-new-completed

- app/views/activities/show.html.erb
> WIP - Working on Image Tiles

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/views/activities/show.html.erb
- app/views/bookings/show.html.erb
- Included the purple form and the component stylesheets
- `number_to_currency(@activity.price)` displays the price in currency format
> WIP - Included a Form component and changed pricing to currency format

- app/controllers/bookings_controller.rb
- app/views/activities/index.html.erb
- app/views/activities/show.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
feature-fixed-bookings-new-problem
> feature-fixed-bookings-new-problem

- app/views/activities/show.html.erb
- Datepicker input form added
- Numeric forms for Adults and Children added
- Numeric forms aligned in a row
- Checkboxes labels can now be triggered
> WIP - Datepicker input form and numeric forms added

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_image.scss
- app/views/activities/show.html.erb
Created dynamic content for image preview.
> WIP - Made an image preview dynamic

- app/controllers/activities_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/activities/index.html.erb
- app/views/activities/landing.html.erb
- app/views/activities/show.html.erb
feature-map-address-implemented-and-misc-debugs
> feature-map-address-implemented-and-misc-debugs

- db/seeds.rb
> corrected minor typo for the museums in seed

- app/controllers/activities_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
> feature-bookings-destroy

- app/assets/stylesheets/components/_card.scss
- app/views/activities/show.html.erb
> WIP - Included a card component block and drew text cards

- app/models/activity.rb
- db/seeds.rb
zh helped to fix the model fetch google images on bollywood farms
> Activitymodel

- db/seeds.rb
> Update activity creation in seeds for paid and unpaid

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/views/activities/show.html.erb
> WIP - Fixed buttons and fonts

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/models/activity.rb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
created meta tags helper, comment out private in activity model, added meta title, description and open graph to head of application.html.erb, created default meta in initializers and meta yml file.
Kindly review thanks!
> include metatagshelper and default_url_options in applications controller

- config/environments/production.rb
- db/schema.rb
now the site is secured with ssl certificate. kindly review thanks
> uncomment out the config.force_ssl=true to allow ssl certificates to run on production

- app/assets/stylesheets/components/_calendar.scss
- app/controllers/activities_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/calendar_test_dont_delete.html.erb
- app/views/bookings/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/simple_calendar/_calendar.html.erb
- app/views/simple_calendar/_month_calendar.html.erb
- app/views/simple_calendar/_week_calendar.html.erb
Miscellaneous changes to navbar and controllers. Styled calendar.
> Feature sunday coding

- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/models/user.rb
- app/views/activities/new.html.erb
- app/views/shared/_navbar.html.erb
Completed organizer authentication/model. Linked create form for organizer. Hide certain pages if not admin.
> Feature sunday coding 2

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_image.scss
- app/assets/stylesheets/components/_widget.scss
- app/views/activities/show.html.erb
- Weather widget embedded into the left side column
- Review cards added
- Review cards now have a random-generated avatar each
- A reviewer has been given a set of randomly generated images
> WIP - Added weather widget and review cards

- app/assets/stylesheets/components/_tables.scss
- app/views/activities/homepage.html.erb
- app/views/activities/show.html.erb
really basic stuffs first to finalize before adjusting the theme.
> minor changes to the position of the all link on homepg, shift the mapbox up into a box, change the heading type of pricing, package, eligibility

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_reviewnew.scss
- app/controllers/reviews_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/activity.rb
- app/models/user.rb
- app/views/activities/new.html.erb
- app/views/reviews/new.html.erb
- app/views/shared/_navbar.html.erb
- package.json
- yarn.lock
review-form-page-creation-styling
> review-form-page-creation-styling

- app/assets/stylesheets/pages/_reviewnew.scss
- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/views/activities/new.html.erb
- app/views/categories/show.html.erb
- app/views/reviews/new.html.erb
- db/seeds.rb
Activity#new works with photo upload
> Activity#new works with photo upload

- app/views/activities/homepage.html.erb
- app/views/bookings/index.html.erb
- app/views/bookmarks/index.html.erb
FIX - Price numbers in currency
> FIX - Price numbers in currency

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_calendar.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/bookings/index.html.erb
- package-lock.json
> Bookingindex

- app/views/activities/show.html.erb
- app/views/bookings/index.html.erb
As per title, for ActivitiesShow page.
> WIP - Allowed Cloudinary image to be loaded

- app/views/activities/show.html.erb
> WIP - Fixed conditional display of Cloudinary image

- app/controllers/activities_controller.rb
- app/models/activity.rb
- app/views/activities/index.html.erb
- yarn.lock
the default filter still needs working
> Adds activity searchable scope and filtering via paid/free

- app/views/shared/_navbar.html.erb
- package.json
- Navbar is now "sticky-top" to prevent covering of elements
- Run "yarn bw" for "yarn build --watch"
> FIX - Replaced fixed behaviour of navbar to sticky and added script

- app/assets/stylesheets/components/_badge.scss
- app/assets/stylesheets/components/_fixation.scss
- app/assets/stylesheets/components/_index.scss
- app/views/bookings/index.html.erb
> WIP - Adjusted responsiveness of calendar

- app/controllers/categories_controller.rb
- app/helpers/application_helper.rb
- app/javascript/controllers/address_autocomplete_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/javascript/controllers/name_button_search_trigger_controller.js
- app/views/activities/index.html.erb
- app/views/shared/_navbar.html.erb
Feature map and miscellaneous changes
> Feature map and miscellaneous changes

- db/seeds.rb
> Add start time to booking seeds

- app/assets/stylesheets/pages/_activityindex.scss
- app/views/activities/index.html.erb
> adjust the search bar position

- app/assets/stylesheets/components/_avatar.scss
- app/views/activities/show.html.erb
Reviews will now display uploaded user avatar.
Yet to do: Default avatar if no uploaded picture. Also, submitted review images.
> ADD - Dynamic avatar for reviews

- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/views/activities/index.html.erb
remove home animation js which was causing errors
> remove homepage js

- app/views/devise/registrations/edit.html.erb
- db/migrate/20221201145931_remove_address_from_user.rb
- db/schema.rb
> removed address from user

- app/views/shared/_offcanvas.html.erb
> Debugging avatar offcanvas

- app/views/activities/homepage.html.erb
> Reaedded jj 6 card

- app/assets/stylesheets/pages/_activityindex.scss
- app/views/activities/index.html.erb
> add magnifying glass to search bar on activities index

- app/views/bookings/index.html.erb
- Calendar badges now link to specific activity page
- Organizer's full name is now displayed
> WIP - BookingsIndex calendar badges now link to activity

- app/views/activities/index.html.erb
> added div filter-container for payment, price and categories

- app/views/activities/show.html.erb
- The two random images have been replaced with the map shifted from the side area
- Replaced if-else statement with a ternary (old code commented out)
> WIP - Replaced random images with shifted map

- app/views/bookings/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
Completed styling for bookings new
> Completed styling for bookings new

- app/controllers/activities_controller.rb
- app/views/activities/show.html.erb
- ActivitesShow now display dynamic counts for reviews and bookings
- Replaced ternary method with old if-else code
> WIP - Dynamic review and booking count

- app/views/activities/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
feature-finished-styling-for-activity-new
> feature-finished-styling-for-activity-new

- app/views/activities/new.html.erb
Added padding to activitynew form
> Added padding to activitynew form

- app/views/activities/show.html.erb
- Site will no longer crash when viewing an activity as a guest
> FIX - Browse ActivitiesShow as a guest

- app/views/activities/homepage.html.erb
> FIX - Image Upload for admin

- app/controllers/reviews_controller.rb
> Minor redirection

- app/assets/stylesheets/components/_button.scss
- app/views/activities/show.html.erb
> Minor styling for show
